/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //use system utility to print message
        //feature2 with new update
        System.out.println(new App().getGreeting());
    }
}
