/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //use system utility to print message 3
        //this an app message extract message3
        System.out.println(new App().getGreeting());
    }
}
